### DISCUSSION TITLE
Execute tests jobs in parallel to be approximately 42% faster

### DISCUSSION THREAD

**Discussion by dianjuar** [jscutlery/devkit#186] [Ideas]
I have a proposition to make [test action](https://github.com/jscutlery/devkit/blob/main/.github/actions/test/action.yml) around 42% faster ⚡.

Currently, we have all the tests on an action. All tests are executed sequentially. The final time execution will be the sum of lint, test, and build execution. For this repository is [2:03min](https://github.com/dianjuar/devkit/runs/6911904887?check_suite_focus=true).

If we run the tests in parallel, the final execution time would be the slowest of the three. For this repository would be the linter with [52.51s](https://github.com/dianjuar/devkit/runs/6911904887?check_suite_focus=true#step:4:147).

---

I propose to create a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) to run all the tests in parallel. I am already implementing this approach on [ngx-deploy-npm](https://github.com/bikecoders/ngx-deploy-npm/actions/runs/2506036067). Graphically it looks like this:

![image](https://user-images.githubusercontent.com/7026066/173987001-8a47c752-f8f2-482c-81ba-c9cd2d268678.png)

Besides the efficiency, we have the following benefits:
  - It's easier to detect what has failed ❌  and what has passed ✅ 
  - It's easier to detect what it's taking longer⏳
  - More transparency on which are the tests ✨

**Comment by dianjuar** [comment]
I have a proposed workflow. I'm going to highlight the differences and features. 

# Proposed Workflow (raw version)

```yml
name: Essential Test

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - name: Lint
        run: npx nx lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup

      - run: npx nx build

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx nx test --code-coverage

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx nx e2e ngx-deploy-npm-e2e
```

# Implementation

```yml
name: PR's
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-test:
    uses: ./.github/workflows/basic-test.yml
  
```

# Principal Differences
## Parallel test

By executing jobs in parallel, we reduce the execution time to the one that takes longer to complete.

## Node V14, 16, 18
Currently, those are the node versions receiving [active maintenance](https://nodejs.org/en/about/releases/). Those versions could be an input to the workflow with those values as default.

![image](https://user-images.githubusercontent.com/7026066/173991803-c3a8c262-f98d-44ed-a6ee-a3800cf2774b.png)

## Execute Lint and Build once

Executing Lint tests in different node versions will result in the same output; nothing will change. The same thing happened with the build, running it in a separate node versions doesn't add too much value, especially if we have our node version specified (using `.npmrc`) for development.
